<?php

namespace Database\Seeders;

use App\Models\Trip;
use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;

class TripSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('trips')->delete();

        $driverId1 = 6;
        $driverId2 = 7;
        $driverId3 = 8;
        $driverId4 = 9;
        $driverId5 = 10;


        $tripsData = [
            // --- DRIVER 3 ---
            // 1. Trip PROSES (AKTIF) untuk Driver 3
            [
                'user_id' => $driverId1,
                'project_name' => 'Distribusi Bahan Baku ke Pabrik Bandung',
                'origin' => 'Bekasi',
                'destination' => 'Bandung',
                'license_plate' => 'B 9876 XYZ',
                'start_km' => 15000,
                'start_km_photo_path' => 'photos/trip_dummy.jpg',
                'start_km_photo_status' => 'pending',
                'start_km_photo_verified_by' => null,
                'start_km_photo_verified_at' => null,
                'start_km_photo_rejection_reason' => null,
                'muat_photo_path' => 'photos/trip_dummy.jpg',
                'muat_photo_status' => 'pending',
                'muat_photo_verified_by' => null,
                'muat_photo_verified_at' => null,
                'muat_photo_rejection_reason' => null,
                'delivery_order_path' => 'photos/trip_dummy.jpg',
                'delivery_order_status' => 'pending',
                'delivery_order_verified_by' => null,
                'delivery_order_verified_at' => null,
                'delivery_order_rejection_reason' => null,
                'timbangan_kendaraan_photo_path' => 'photos/trip_dummy.jpg',
                'timbangan_kendaraan_photo_status' => 'pending',
                'timbangan_kendaraan_photo_verified_by' => null,
                'timbangan_kendaraan_photo_verified_at' => null,
                'timbangan_kendaraan_photo_rejection_reason' => null,
                'segel_photo_path' => 'photos/trip_dummy.jpg',
                'segel_photo_status' => 'pending',
                'segel_photo_verified_by' => null,
                'segel_photo_verified_at' => null,
                'segel_photo_rejection_reason' => null,
                'bongkar_photo_path' => null,
                'bongkar_photo_status' => 'pending',
                'bongkar_photo_verified_by' => null,
                'bongkar_photo_verified_at' => null,
                'bongkar_photo_rejection_reason' => null,
                'end_km' => null,
                'end_km_photo_path' => null,
                'end_km_photo_status' => 'pending',
                'end_km_photo_verified_by' => null,
                'end_km_photo_verified_at' => null,
                'end_km_photo_rejection_reason' => null,
                'delivery_letter_path' => null,
                'delivery_letter_status' => 'pending',
                'delivery_letter_verified_by' => null,
                'delivery_letter_verified_at' => null,
                'delivery_letter_rejection_reason' => null,
                'status_trip' => 'proses',
                'jenis_trip' => 'muatan perusahan',
                'status_lokasi' => 'menuju lokasi bongkar',
                'status_muatan' => 'termuat',
                'created_at' => now()->subDays(1),
                'updated_at' => now()->subHour(),
            ],
            // 2. Trip SELESAI untuk Driver 3
            [
                'user_id' => $driverId1,
                'project_name' => 'Pengiriman Logistik Gudang Cikarang (Lama)',
                'origin' => 'Jakarta',
                'destination' => 'Cikarang',
                'license_plate' => 'B 1111 ABC',
                'start_km' => 10000,
                'start_km_photo_path' => 'photos/trip_dummy.jpg',
                'start_km_photo_status' => 'pending',
                'start_km_photo_verified_by' => null,
                'start_km_photo_verified_at' => null,
                'start_km_photo_rejection_reason' => null,
                'muat_photo_path' => 'photos/trip_dummy.jpg',
                'muat_photo_status' => 'pending',
                'muat_photo_verified_by' => null,
                'muat_photo_verified_at' => null,
                'muat_photo_rejection_reason' => null,
                'delivery_order_path' => 'photos/trip_dummy.jpg',
                'delivery_order_status' => 'pending',
                'delivery_order_verified_by' => null,
                'delivery_order_verified_at' => null,
                'delivery_order_rejection_reason' => null,
                'timbangan_kendaraan_photo_path' => 'photos/trip_dummy.jpg',
                'timbangan_kendaraan_photo_status' => 'pending',
                'timbangan_kendaraan_photo_verified_by' => null,
                'timbangan_kendaraan_photo_verified_at' => null,
                'timbangan_kendaraan_photo_rejection_reason' => null,
                'segel_photo_path' => 'photos/trip_dummy.jpg',
                'segel_photo_status' => 'pending',
                'segel_photo_verified_by' => null,
                'segel_photo_verified_at' => null,
                'segel_photo_rejection_reason' => null,
                'bongkar_photo_path' => ['photos/trip_dummy.jpg', 'photos/trip_dummy.jpg'],
                'bongkar_photo_status' => 'pending',
                'bongkar_photo_verified_by' => null,
                'bongkar_photo_verified_at' => null,
                'bongkar_photo_rejection_reason' => null,
                'end_km' => 10100,
                'end_km_photo_path' => 'photos/trip_dummy.jpg',
                'end_km_photo_status' => 'pending',
                'end_km_photo_verified_by' => null,
                'end_km_photo_verified_at' => null,
                'end_km_photo_rejection_reason' => null,
                'delivery_letter_path' => json_encode(['initial_letters' => ['letters/dummy.jpg'], 'final_letters' => ['letters/dummy.jpg']]),
                'delivery_letter_status' => 'pending',
                'delivery_letter_verified_by' => null,
                'delivery_letter_verified_at' => null,
                'delivery_letter_rejection_reason' => null,
                'status_trip' => 'selesai',
                'jenis_trip' => 'muatan perusahan',
                'status_lokasi' => 'di lokasi bongkar',
                'status_muatan' => 'selesai bongkar',
                'created_at' => now()->subDays(6),
                'updated_at' => null,
            ],

            // --- DRIVER 4 ---
            // 3. Trip PROSES (AKTIF) untuk Driver 4
            [
                'user_id' => $driverId2,
                'project_name' => 'Antar Barang Retail ke Surabaya',
                'origin' => 'Semarang',
                'destination' => 'Surabaya',
                'license_plate' => 'H 1234 AB',
                'start_km' => 78200,
                'start_km_photo_path' => 'photos/trip_dummy.jpg',
                'start_km_photo_status' => 'rejected',
                'start_km_photo_verified_by' => null,
                'start_km_photo_verified_at' => now()->subHours(3),
                'start_km_photo_rejection_reason' => 'Foto KM Awal buram.',
                'muat_photo_path' => null,
                'muat_photo_status' => 'pending',
                'muat_photo_verified_by' => null,
                'muat_photo_verified_at' => null,
                'muat_photo_rejection_reason' => null,
                'delivery_order_path' => null,
                'delivery_order_status' => 'pending',
                'delivery_order_verified_by' => null,
                'delivery_order_verified_at' => null,
                'delivery_order_rejection_reason' => null,
                'timbangan_kendaraan_photo_path' => null,
                'timbangan_kendaraan_photo_status' => 'pending',
                'timbangan_kendaraan_photo_verified_by' => null,
                'timbangan_kendaraan_photo_verified_at' => null,
                'timbangan_kendaraan_photo_rejection_reason' => null,
                'segel_photo_path' => null,
                'segel_photo_status' => 'pending',
                'segel_photo_verified_by' => null,
                'segel_photo_verified_at' => null,
                'segel_photo_rejection_reason' => null,
                'bongkar_photo_path' => null,
                'bongkar_photo_status' => 'pending',
                'bongkar_photo_verified_by' => null,
                'bongkar_photo_verified_at' => null,
                'bongkar_photo_rejection_reason' => null,
                'end_km' => null,
                'end_km_photo_path' => null,
                'end_km_photo_status' => 'pending',
                'end_km_photo_verified_by' => null,
                'end_km_photo_verified_at' => null,
                'end_km_photo_rejection_reason' => null,
                'delivery_letter_path' => null,
                'delivery_letter_status' => 'pending',
                'delivery_letter_verified_by' => null,
                'delivery_letter_verified_at' => null,
                'delivery_letter_rejection_reason' => null,
                'status_trip' => 'proses',
                'jenis_trip' => 'muatan perusahan',
                'status_lokasi' => 'di lokasi muat',
                'status_muatan' => 'proses muat',
                'created_at' => now()->subHours(8),
                'updated_at' => now()->subHours(3),
            ],
            // 4. Trip TERSEDIA untuk Driver 4
            [
                'user_id' => $driverId2,
                'project_name' => 'Pengiriman Berikutnya ke Cirebon',
                'origin' => 'Bandung',
                'destination' => 'Cirebon',
                'license_plate' => null,
                'start_km' => null,
                'start_km_photo_path' => null,
                'start_km_photo_status' => 'pending',
                'start_km_photo_verified_by' => null,
                'start_km_photo_verified_at' => null,
                'start_km_photo_rejection_reason' => null,
                'muat_photo_path' => null,
                'muat_photo_status' => 'pending',
                'muat_photo_verified_by' => null,
                'muat_photo_verified_at' => null,
                'muat_photo_rejection_reason' => null,
                'delivery_order_path' => null,
                'delivery_order_status' => 'pending',
                'delivery_order_verified_by' => null,
                'delivery_order_verified_at' => null,
                'delivery_order_rejection_reason' => null,
                'timbangan_kendaraan_photo_path' => null,
                'timbangan_kendaraan_photo_status' => 'pending',
                'timbangan_kendaraan_photo_verified_by' => null,
                'timbangan_kendaraan_photo_verified_at' => null,
                'timbangan_kendaraan_photo_rejection_reason' => null,
                'segel_photo_path' => null,
                'segel_photo_status' => 'pending',
                'segel_photo_verified_by' => null,
                'segel_photo_verified_at' => null,
                'segel_photo_rejection_reason' => null,
                'bongkar_photo_path' => null,
                'bongkar_photo_status' => 'pending',
                'bongkar_photo_verified_by' => null,
                'bongkar_photo_verified_at' => null,
                'bongkar_photo_rejection_reason' => null,
                'end_km' => null,
                'end_km_photo_path' => null,
                'end_km_photo_status' => 'pending',
                'end_km_photo_verified_by' => null,
                'end_km_photo_verified_at' => null,
                'end_km_photo_rejection_reason' => null,
                'delivery_letter_path' => null,
                'delivery_letter_status' => 'pending',
                'delivery_letter_verified_by' => null,
                'delivery_letter_verified_at' => null,
                'delivery_letter_rejection_reason' => null,
                'status_trip' => 'tersedia',
                'jenis_trip' => 'muatan perusahan',
                'status_lokasi' => null,
                'status_muatan' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // --- DRIVER 5 ---
            // 5. Trip SELESAI untuk Driver 5
            [
                'user_id' => $driverId3,
                'project_name' => 'Pengiriman Material Proyek ke Yogyakarta',
                'origin' => 'Solo',
                'destination' => 'Yogyakarta',
                'license_plate' => 'AD 5555 CD',
                'start_km' => 125000,
                'start_km_photo_path' => 'photos/trip_dummy.jpg',
                'start_km_photo_status' => 'pending',
                'start_km_photo_verified_by' => null,
                'start_km_photo_verified_at' => null,
                'start_km_photo_rejection_reason' => null,
                'muat_photo_path' => 'photos/trip_dummy.jpg',
                'muat_photo_status' => 'pending',
                'muat_photo_verified_by' => null,
                'muat_photo_verified_at' => null,
                'muat_photo_rejection_reason' => null,
                'delivery_order_path' => 'photos/trip_dummy.jpg',
                'delivery_order_status' => 'pending',
                'delivery_order_verified_by' => null,
                'delivery_order_verified_at' => null,
                'delivery_order_rejection_reason' => null,
                'timbangan_kendaraan_photo_path' => 'photos/trip_dummy.jpg',
                'timbangan_kendaraan_photo_status' => 'pending',
                'timbangan_kendaraan_photo_verified_by' => null,
                'timbangan_kendaraan_photo_verified_at' => null,
                'timbangan_kendaraan_photo_rejection_reason' => null,
                'segel_photo_path' => 'photos/trip_dummy.jpg',
                'segel_photo_status' => 'pending',
                'segel_photo_verified_by' => null,
                'segel_photo_verified_at' => null,
                'segel_photo_rejection_reason' => null,
                'bongkar_photo_path' => ['photos/trip_dummy.jpg', 'photos/trip_dummy.jpg'],
                'bongkar_photo_status' => 'pending',
                'bongkar_photo_verified_by' => null,
                'bongkar_photo_verified_at' => null,
                'bongkar_photo_rejection_reason' => null,
                'end_km' => 125150,
                'end_km_photo_path' => 'photos/trip_dummy.jpg',
                'end_km_photo_status' => 'pending',
                'end_km_photo_verified_by' => null,
                'end_km_photo_verified_at' => null,
                'end_km_photo_rejection_reason' => null,
                'delivery_letter_path' => json_encode(['initial_letters' => ['letters/dummy.jpg'], 'final_letters' => ['letters/dummy.jpg']]),
                'delivery_letter_status' => 'pending',
                'delivery_letter_verified_by' => null,
                'delivery_letter_verified_at' => null,
                'delivery_letter_rejection_reason' => null,
                'status_trip' => 'selesai',
                'jenis_trip' => 'muatan perusahan',
                'status_lokasi' => 'di lokasi bongkar',
                'status_muatan' => 'selesai bongkar',
                'created_at' => now()->subDays(3),
                'updated_at' => null,
            ],
            // 6. Trip SELESAI (Muatan Driver) untuk Driver 5
            [
                'user_id' => $driverId3,
                'project_name' => 'Muatan Pribadi Driver ke Cirebon (Lama)',
                'origin' => 'Tegal',
                'destination' => 'Cirebon',
                'license_plate' => 'G 4444 EF',
                'start_km' => 20000,
                'start_km_photo_path' => 'photos/trip_dummy.jpg',
                'start_km_photo_status' => 'pending',
                'start_km_photo_verified_by' => null,
                'start_km_photo_verified_at' => null,
                'start_km_photo_rejection_reason' => null,
                'muat_photo_path' => 'photos/trip_dummy.jpg',
                'muat_photo_status' => 'pending',
                'muat_photo_verified_by' => null,
                'muat_photo_verified_at' => null,
                'muat_photo_rejection_reason' => null,
                'delivery_order_path' => 'photos/trip_dummy.jpg',
                'delivery_order_status' => 'pending',
                'delivery_order_verified_by' => null,
                'delivery_order_verified_at' => null,
                'delivery_order_rejection_reason' => null,
                'timbangan_kendaraan_photo_path' => 'photos/trip_dummy.jpg',
                'timbangan_kendaraan_photo_status' => 'pending',
                'timbangan_kendaraan_photo_verified_by' => null,
                'timbangan_kendaraan_photo_verified_at' => null,
                'timbangan_kendaraan_photo_rejection_reason' => null,
                'segel_photo_path' => 'photos/trip_dummy.jpg',
                'segel_photo_status' => 'pending',
                'segel_photo_verified_by' => null,
                'segel_photo_verified_at' => null,
                'segel_photo_rejection_reason' => null,
                'bongkar_photo_path' => ['photos/trip_dummy.jpg', 'photos/trip_dummy.jpg'],
                'bongkar_photo_status' => 'pending',
                'bongkar_photo_verified_by' => null,
                'bongkar_photo_verified_at' => null,
                'bongkar_photo_rejection_reason' => null,
                'end_km' => 20100,
                'end_km_photo_path' => 'photos/trip_dummy.jpg',
                'end_km_photo_status' => 'pending',
                'end_km_photo_verified_by' => null,
                'end_km_photo_verified_at' => null,
                'end_km_photo_rejection_reason' => null,
                'delivery_letter_path' => null,
                'delivery_letter_status' => 'pending',
                'delivery_letter_verified_by' => null,
                'delivery_letter_verified_at' => null,
                'delivery_letter_rejection_reason' => null,
                'status_trip' => 'selesai',
                'jenis_trip' => 'muatan driver',
                'status_lokasi' => 'di lokasi bongkar',
                'status_muatan' => 'selesai bongkar',
                'created_at' => null,
                'updated_at' => null,
            ],

            // --- DRIVER 6 ---
            // 7. Trip PROSES (AKTIF) untuk Driver 6
            [
                'user_id' => $driverId4,
                'project_name' => 'Ekspedisi Barang Elektronik ke Malang',
                'origin' => 'Surabaya',
                'destination' => 'Malang',
                'license_plate' => 'L 7777 GH',
                'start_km' => 5000,
                'start_km_photo_path' => 'photos/trip_dummy.jpg',
                'start_km_photo_status' => 'pending',
                'start_km_photo_verified_by' => null,
                'start_km_photo_verified_at' => null,
                'start_km_photo_rejection_reason' => null,
                'muat_photo_path' => null,
                'muat_photo_status' => 'pending',
                'muat_photo_verified_by' => null,
                'muat_photo_verified_at' => null,
                'muat_photo_rejection_reason' => null,
                'delivery_order_path' => null,
                'delivery_order_status' => 'pending',
                'delivery_order_verified_by' => null,
                'delivery_order_verified_at' => null,
                'delivery_order_rejection_reason' => null,
                'timbangan_kendaraan_photo_path' => null,
                'timbangan_kendaraan_photo_status' => 'pending',
                'timbangan_kendaraan_photo_verified_by' => null,
                'timbangan_kendaraan_photo_verified_at' => null,
                'timbangan_kendaraan_photo_rejection_reason' => null,
                'segel_photo_path' => null,
                'segel_photo_status' => 'pending',
                'segel_photo_verified_by' => null,
                'segel_photo_verified_at' => null,
                'segel_photo_rejection_reason' => null,
                'bongkar_photo_path' => null,
                'bongkar_photo_status' => 'pending',
                'bongkar_photo_verified_by' => null,
                'bongkar_photo_verified_at' => null,
                'bongkar_photo_rejection_reason' => null,
                'end_km' => null,
                'end_km_photo_path' => null,
                'end_km_photo_status' => 'pending',
                'end_km_photo_verified_by' => null,
                'end_km_photo_verified_at' => null,
                'end_km_photo_rejection_reason' => null,
                'delivery_letter_path' => null,
                'delivery_letter_status' => 'pending',
                'delivery_letter_verified_by' => null,
                'delivery_letter_verified_at' => null,
                'delivery_letter_rejection_reason' => null,
                'status_trip' => 'proses',
                'jenis_trip' => 'muatan perusahan',
                'status_lokasi' => 'menuju lokasi muat',
                'status_muatan' => 'kosong',
                'created_at' => now()->subHour(),
                'updated_at' => now()->subHour(),
            ],

            // --- DRIVER 7 ---
            // 8. Trip TERSEDIA untuk Driver 7
            [
                'user_id' => $driverId5,
                'project_name' => 'Pengiriman Pupuk ke Area Perkebunan',
                'origin' => 'Gresik',
                'destination' => 'Lamongan',
                'license_plate' => null,
                'start_km' => null,
                'start_km_photo_path' => null,
                'start_km_photo_status' => 'pending',
                'start_km_photo_verified_by' => null,
                'start_km_photo_verified_at' => null,
                'start_km_photo_rejection_reason' => null,
                'muat_photo_path' => null,
                'muat_photo_status' => 'pending',
                'muat_photo_verified_by' => null,
                'muat_photo_verified_at' => null,
                'muat_photo_rejection_reason' => null,
                'delivery_order_path' => null,
                'delivery_order_status' => 'pending',
                'delivery_order_verified_by' => null,
                'delivery_order_verified_at' => null,
                'delivery_order_rejection_reason' => null,
                'timbangan_kendaraan_photo_path' => null,
                'timbangan_kendaraan_photo_status' => 'pending',
                'timbangan_kendaraan_photo_verified_by' => null,
                'timbangan_kendaraan_photo_verified_at' => null,
                'timbangan_kendaraan_photo_rejection_reason' => null,
                'segel_photo_path' => null,
                'segel_photo_status' => 'pending',
                'segel_photo_verified_by' => null,
                'segel_photo_verified_at' => null,
                'segel_photo_rejection_reason' => null,
                'bongkar_photo_path' => ['photos/trip_dummy.jpg', 'photos/trip_dummy.jpg'],
                'bongkar_photo_status' => 'pending',
                'bongkar_photo_verified_by' => null,
                'bongkar_photo_verified_at' => null,
                'bongkar_photo_rejection_reason' => null,
                'end_km' => null,
                'end_km_photo_path' => null,
                'end_km_photo_status' => 'pending',
                'end_km_photo_verified_by' => null,
                'end_km_photo_verified_at' => null,
                'end_km_photo_rejection_reason' => null,
                'delivery_letter_path' => null,
                'delivery_letter_status' => 'pending',
                'delivery_letter_verified_by' => null,
                'delivery_letter_verified_at' => null,
                'delivery_letter_rejection_reason' => null,
                'status_trip' => 'tersedia',
                'jenis_trip' => 'muatan perusahan',
                'status_lokasi' => null,
                'status_muatan' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 9. Trip SELESAI untuk Driver 7
            [
                'user_id' => $driverId5,
                'project_name' => 'Trip Kilat Antar Dokumen (Lama)',
                'origin' => 'Jakarta Pusat',
                'destination' => 'Jakarta Barat',
                'license_plate' => 'B 3322 JKL',
                'start_km' => 95000,
                'start_km_photo_path' => 'photos/trip_dummy.jpg',
                'start_km_photo_status' => 'pending',
                'start_km_photo_verified_by' => null,
                'start_km_photo_verified_at' => null,
                'start_km_photo_rejection_reason' => null,
                'muat_photo_path' => 'photos/trip_dummy.jpg',
                'muat_photo_status' => 'pending',
                'muat_photo_verified_by' => null,
                'muat_photo_verified_at' => null,
                'muat_photo_rejection_reason' => null,
                'delivery_order_path' => 'photos/trip_dummy.jpg',
                'delivery_order_status' => 'pending',
                'delivery_order_verified_by' => null,
                'delivery_order_verified_at' => null,
                'delivery_order_rejection_reason' => null,
                'timbangan_kendaraan_photo_path' => 'photos/trip_dummy.jpg',
                'timbangan_kendaraan_photo_status' => 'pending',
                'timbangan_kendaraan_photo_verified_by' => null,
                'timbangan_kendaraan_photo_verified_at' => null,
                'timbangan_kendaraan_photo_rejection_reason' => null,
                'segel_photo_path' => 'photos/trip_dummy.jpg',
                'segel_photo_status' => 'pending',
                'segel_photo_verified_by' => null,
                'segel_photo_verified_at' => null,
                'segel_photo_rejection_reason' => null,
                'bongkar_photo_path' => ['photos/trip_dummy.jpg', 'photos/trip_dummy.jpg'],
                'bongkar_photo_status' => 'pending',
                'bongkar_photo_verified_by' => null,
                'bongkar_photo_verified_at' => null,
                'bongkar_photo_rejection_reason' => null,
                'end_km' => 95025,
                'end_km_photo_path' => 'photos/trip_dummy.jpg',
                'end_km_photo_status' => 'pending',
                'end_km_photo_verified_by' => null,
                'end_km_photo_verified_at' => null,
                'end_km_photo_rejection_reason' => null,
                'delivery_letter_path' => json_encode(['initial_letters' => ['letters/dummy.jpg'], 'final_letters' => ['letters/dummy.jpg']]),
                'delivery_letter_status' => 'pending',
                'delivery_letter_verified_by' => null,
                'delivery_letter_verified_at' => null,
                'delivery_letter_rejection_reason' => null,
                'status_trip' => 'selesai',
                'jenis_trip' => 'muatan driver',
                'status_lokasi' => null,
                'status_muatan' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            // 10. Trip TERSEDIA (Muatan Driver) untuk Driver 7
            [
                'user_id' => $driverId5,
                'project_name' => 'Orderan pribadi ke Bogor',
                'origin' => 'Depok',
                'destination' => 'Bogor',
                'license_plate' => null,
                'start_km' => null,
                'start_km_photo_path' => null,
                'start_km_photo_status' => 'pending',
                'start_km_photo_verified_by' => null,
                'start_km_photo_verified_at' => null,
                'start_km_photo_rejection_reason' => null,
                'muat_photo_path' => null,
                'muat_photo_status' => 'pending',
                'muat_photo_verified_by' => null,
                'muat_photo_verified_at' => null,
                'muat_photo_rejection_reason' => null,
                'delivery_order_path' => null,
                'delivery_order_status' => 'pending',
                'delivery_order_verified_by' => null,
                'delivery_order_verified_at' => null,
                'delivery_order_rejection_reason' => null,
                'timbangan_kendaraan_photo_path' => null,
                'timbangan_kendaraan_photo_status' => 'pending',
                'timbangan_kendaraan_photo_verified_by' => null,
                'timbangan_kendaraan_photo_verified_at' => null,
                'timbangan_kendaraan_photo_rejection_reason' => null,
                'segel_photo_path' => null,
                'segel_photo_status' => 'pending',
                'segel_photo_verified_by' => null,
                'segel_photo_verified_at' => null,
                'segel_photo_rejection_reason' => null,
                'bongkar_photo_path' => null,
                'bongkar_photo_status' => 'pending',
                'bongkar_photo_verified_by' => null,
                'bongkar_photo_verified_at' => null,
                'bongkar_photo_rejection_reason' => null,
                'end_km' => null,
                'end_km_photo_path' => null,
                'end_km_photo_status' => 'pending',
                'end_km_photo_verified_by' => null,
                'end_km_photo_verified_at' => null,
                'end_km_photo_rejection_reason' => null,
                'delivery_letter_path' => null,
                'delivery_letter_status' => 'pending',
                'delivery_letter_verified_by' => null,
                'delivery_letter_verified_at' => null,
                'delivery_letter_rejection_reason' => null,
                'status_trip' => 'tersedia',
                'jenis_trip' => 'muatan driver',
                'status_lokasi' => null,
                'status_muatan' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];
        foreach ($tripsData as $tripData) {
            Trip::create($tripData);
        }
    }
}
